In [28]:
import pandas as pd
import numpy as np
from statsmodels.formula.api import ols

In [29]:
data = pd.read_csv('data.csv')
data.columns = ['StandardOrder', 'ActualOrder', 'BallType', 'DropHeight', 'ReleaseAngle', 'Replication', 'BounceHeight']
data

,StandardOrder,ActualOrder,BallType,DropHeight,ReleaseAngle,Replication,BounceHeight
0,1,18,Golf,1.0,0.000000,1,0.33
1,2,24,Tennis,1.0,0.000000,1,0.61
2,3,1,Golf,1.5,0.000000,1,0.55
3,4,16,Tennis,1.5,0.000000,1,0.72
4,5,7,Golf,1.0,1.570796,1,0.31
5,6,17,Tennis,1.0,1.570796,1,0.64
6,7,13,Golf,1.5,1.570796,1,0.54
7,8,9,Tennis,1.5,1.570796,1,0.77
8,9,10,Golf,1.0,0.000000,2,0.36
9,10,8,Tennis,1.0,0.000000,2,0.59
10,11,21,Golf,1.5,0.000000,2,0.56
11,12,23,Tennis,1.5,0.000000,2,0.72
12,13,5,Golf,1.0,1.570796,2,0.32
13,14,4,Tennis,1.0,1.570796,2,0.67
14,15,15,Golf,1.5,1.570796,2,0.59
15,16,19,Tennis,1.5,1.570796,2,0.74
16,17,6,Golf,1.0,0.000000,3,0.31
17,18,3,Tennis,1.0,0.000000,3,0.61
18,19,12,Golf,1.5,0.000000,3,0.56
19,20,2,Tennis,1.5,0.000000,3,0.77
20,21,11,Golf,1.0,1.570796,3,0.29
21,22,14,Tennis,1.0,1.570796,3,0.65
22,23,20,Golf,1.5,1.570796,3,0.54
23,24,22,Tennis,1.5,1.570796,3,0.76

In [30]:
design_table = data[['BallType', 'DropHeight', 'ReleaseAngle', 'BounceHeight']].copy()
design_table['BallType'] = design_table['BallType'].apply(lambda x: 1 if x == 'Tennis' else -1)
design_table['DropHeight'] = design_table['DropHeight'].apply(lambda x: 1 if x == 1.5 else -1)
design_table['ReleaseAngle'] = design_table['ReleaseAngle'].apply(lambda x: -1 if x == 0 else 1)
design_table

    BallType  DropHeight  ReleaseAngle  BounceHeight
0         -1          -1            -1          0.33
1          1          -1            -1          0.61
2         -1           1            -1          0.55
3          1           1            -1          0.72
4         -1          -1             1          0.31
5          1          -1             1          0.64
6         -1           1             1          0.54
7          1           1             1          0.77
8         -1          -1            -1          0.36
9          1          -1            -1          0.59
10        -1           1            -1          0.56
11         1           1            -1          0.72
12        -1          -1             1          0.32
13         1          -1             1          0.67
14        -1           1             1          0.59
15         1           1             1          0.74
16        -1          -1            -1          0.31
17         1          -1            -1          0.61
18        -1           1            -1          0.56
19         1           1            -1          0.77
20        -1          -1             1          0.29
21         1          -1             1          0.65
22        -1           1             1          0.54
23         1           1             1          0.76

In [31]:
# geometric illustration (cube plot)
# main effects
# calculate the 3 2-factor interactions, and the 1 3-factor interaction
# main effects and interactions using least squares
# computer verification

In [32]:
# # main effects

# tennis_avg = df[df['Ball Type'] == 'Tennis']['Bounce Height (m)'].mean()
# drop_height_avg = df[df['Drop Height (m)'] == 1.5]['Bounce Height (m)'].mean()
# release_angle_avg = df[df['Release Angle (rad)'] != 0]['Bounce Height (m)'].mean()

# print(f'Tennis: {tennis_avg} m')
# print(f'Drop Height: {drop_height_avg} m')
# print(f'Release Angle: {release_angle_avg} m')

In [33]:
# interaction effects

In [36]:
model = ols('BounceHeight ~ BallType * DropHeight * ReleaseAngle', data=design_table).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           BounceHeight   R-squared:                       0.989
Model:                            OLS   Adj. R-squared:                  0.985
Method:                 Least Squares   F-statistic:                     212.2
Date:                Mon, 09 Dec 2024   Prob (F-statistic):           1.44e-14
Time:                        15:15:12   Log-Likelihood:                 64.825
No. Observations:                  24   AIC:                            -113.7
Df Residuals:                      16   BIC:                            -104.2
Df Model:                           7
Covariance Type:            nonrobust
====================================================================================================
                                       coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------
Intercept                            0.5629      0.004    138.610      0.000       0.554       0.572
BallType                             0.1246      0.004     30.677      0.000       0.116       0.133
DropHeight                           0.0887      0.004     21.853      0.000       0.080       0.097
BallType:DropHeight                 -0.0296      0.004     -7.284      0.000      -0.038      -0.021
ReleaseAngle                         0.0054      0.004      1.334      0.201      -0.003       0.014
BallType:ReleaseAngle                0.0121      0.004      2.975      0.009       0.003       0.021
DropHeight:ReleaseAngle             -0.0004      0.004     -0.103      0.920      -0.009       0.008
BallType:DropHeight:ReleaseAngle    -0.0071      0.004     -1.744      0.100      -0.016       0.002
==============================================================================
Omnibus:                        1.896   Durbin-Watson:                   2.088
Prob(Omnibus):                  0.388   Jarque-Bera (JB):                1.661
Skew:                           0.559   Prob(JB):                        0.436
Kurtosis:                       2.360   Cond. No.                         1.00
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
# make scatter plot of the 3 factors and the response

In [ ]:
# slide 104 and downwards